### ISSUE TITLE
Question: Raspbian Lite and Installer

### ISSUE THREAD

**Issue by phuzz** [aceisace/Inky-Calendar#131]
If you install the non-desktop version of Raspbian, `git` and `python3-pip` are not installed by default. As the installer doesn't check for their presence, it fails to install (and produces errors), but still reports to have worked successfully.
As the instructions clearly state to install the desktop version, I realise this is technically an unsupported installation, and it's just a little issue so please don't spend too much time on it ;)

Installer log below
```
pi@raspberrypi:~ $ bash -c "$(curl -sL https://raw.githubusercontent.com/aceisace/Inky-Calendar/master/Installer.sh)"
Please select an option from below:
Enter [1] to update Inky-Calendar software
Enter [2] to install Inky-Calendar software
Enter [3] to uninstall Inky-Calendar software
Confirm your selection with [ENTER]
Waiting for input...  2
Would you like to update and upgrade the operating system first?
It is not scrictly required, but highly recommended.
Please note that updating may take quite some time, in rare cases up to 1 hour.
Please type [y] for yes or [n] for no and confirm your selection with [ENTER]
Waiting for input...  n
Cloning Inky-Calendar repo from Github
bash: line 83: git: command not found
Installing requirements for Inky-Calendar software
bash: line 87: cd: /home/pi/Inky-Calendar: No such file or directory
ln: target '/home/pi/Inky-Calendar/modules/' is not a directory: No such file or directory
ln: target '/home/pi/Inky-Calendar/modules/' is not a directory: No such file or directory

Do you want the software to start automatically at boot?
Press [Y] for yes or [N] for no. The default option is yes
Confirm your selection with [ENTER]
Waiting for input...  y
Setting up auto-start of script at boot
Reading package lists... Done
Building dependency tree
Reading state information... Done
supervisor is already the newest version (3.3.5-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Job for supervisor.service failed because the control process exited with error code.
See "systemctl status supervisor.service" and "journalctl -xe" for details.

The install was successful.
You can now add your personal details in the settings file
located in Inky-Calendar/settings/settings.py
If you want to add your details now, selet an option from below
Type [1] to open the settings-web-UI (user-fiendly)
Type [2] to open settings file with nano (can be run on SSH)
Type [3] to open settings file with python3 (can be run on SSH)
Leave empty to skip this step
Confirm your selection with [ENTER]
Waiting for input...  2
Opening settings file with nano
You can test if the programm works by running:
python3 /home/pi/Inky-Calendar/modules/inkycal.py
```

Assuming you then install `git` you still get errors for missing pip3
(I've also just noticed that in the second to last line of the output, program is spelt 'programm')

```
Waiting for input...  n
Cloning Inky-Calendar repo from Github
Cloning into 'Inky-Calendar'...
remote: Enumerating objects: 52, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 6106 (delta 22), reused 13 (delta 7), pack-reused 6054
Receiving objects: 100% (6106/6106), 135.62 MiB | 4.74 MiB/s, done.
Resolving deltas: 100% (3480/3480), done.
Checking out files: 100% (63/63), done.
Installing requirements for Inky-Calendar software
bash: line 87: pip3: command not found

Do you want the software to start automatically at boot?
Press [Y] for yes or [N] for no. The default option is yes
Confirm your selection with [ENTER]
```

Installing `git` and `pip3` allows the install to work, but on testing the program, I find that there's a lot more that isn't installed in the non-desktop version. (I'll admit, I thought it was just going to be git when I opened this issue). Rather than paste all the various errors I've encountered, I'll just list the dependencies that I had to install:
Via apt: `libtiff5 libopenjp2-7 libatlas-base-dev`
Via pip: `numpy spidev rpi.GPIO`

Again, I realise that this version of Rasbian isn't supported, so feel free to just close this issue. Hopefully it'll still be indexed so it might serve as a warning to others.

**Comment by aceisace** [comment]
@phuzz  Apologies for the late reply, been a bit busy with non-dev stuff the past weeks.
Support for Raspbian Lite was dropped on purpose due to the technical difficulty of checking the existence of packages. With every new Lite release, the installer had to be re-adjusted to install things that were not pre-installed in the new version.

If it was just a handful of packages, it would be fine, but Pillow (fork of PIL, python imaging library), which is also one of the core libraries used by Inkycal, also has a bunch of requirements that keep changing with each release. What's more is that the name of some dependencies kept changing, leading to even more errors during installation on Lite.

To make the project more easier to maintain, support for Raspbian Lite was offiically dropped.
You can attempt to get this running on Lite by installing everything manually that is missing, but this is only for advanced users.

The recommended way to install this on Lite looks something like:
* installing git
* installing pip3
* installing requirements from requirements.txt
* attempt to run Inkycal
* install each missing package manually that throws an error
