### ISSUE TITLE
BETA: Fix: Overlapping event rows

### ISSUE THREAD

**Issue by vitasam** [aceisace/Inky-Calendar#138]
If there are 31 days in a month and the month starts on Saturday, then the Calendar needs 7 rows, not 6:
![canvas_original](https://user-images.githubusercontent.com/5597505/90474520-1f69e400-e12e-11ea-8394-29038bf775b3.png)
![canvas](https://user-images.githubusercontent.com/5597505/90474522-20027a80-e12e-11ea-9246-98b25b3e07e2.png)
#134

**Comment by aceisace** [comment]
@vitasam Thanks for the report of this issue. I've added the bugfix for the overlapping events in this commit: 
https://github.com/aceisace/Inky-Calendar/commit/2a2ad18a0370a4168aac21938e9cba8bc0657aca
I've done some testing on these myself. The events should not be overlapping with the Calendar anymore.

I'm closing this issue since the issue has been resolved in /release/2.0.0. If you feel a need to re-open this issue, please feel free to do so again.

**Comment by vitasam** [comment]
Thank you!
