### ISSUE TITLE
"31 is not in list"

### ISSUE THREAD

**Issue by clone545** [aceisace/Inky-Calendar#139]
**Describe the bug**
Screen now only shows "31 is not in list" instead of calendar, though it appears weather and RSS feeds are still working.

**To Reproduce**
No idea, it's been working fine for months and no changes to config have been made.
Issue first noticed on 31st August, assumed issue with date 31st, but issue persists now and through multiple reboots.

**Screenshots**
![image](https://user-images.githubusercontent.com/8034367/92103459-e9885900-edd7-11ea-9707-1e2dbbeb013d.png)

**Comment by aceisace** [comment]
@clone545 Thanks for the report.
I've implemented the bugfix for this issue in the next release (see here: https://github.com/aceisace/Inky-Calendar/commit/2a2ad18a0370a4168aac21938e9cba8bc0657aca).
I'm closing this issue now since this problem could be resolved. If you feel a need to re-open this issue, please feel free to do so. Thank in advance.
